# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "CHP203: Parallel Optimization Techniques"
site_url: https://dssgabriel.github.io/CHP203-TOP
site_author: Hugo Taboada, Gabriel Dos Santos

repo_name: dssgabriel/CHP203-TOP
repo_url: https://github.com/dssgabriel/chp203-top

copyright: Copyright &copy; 2024 - 2025, Hugo Taboada & Gabriel Dos Santos

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - tables
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # (1)!
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Repository and tools: repository_and_tools.md
  - "Lab 1: Toolchains and HPC environment": lab1.md
  - "Lab 2: Methodology for data visualization": lab2.md
  - "Lab 3: Memory and data structure layouts": lab3.md
  - "Lab 4: Distributed programming models": lab4.md
  - "Lab 5: Shared-memory parallelism": lab5.md
  - "Lab 6: Vectorization & ILP": lab6.md
